### ISSUE TITLE
Wysyłanie listów z okna szczegółów organizacji

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/watchdog-kj-kultura#21]
Szanowni,

Uważam za zbyteczne konieczność otwierania dodatkowego okna, aby móc wysłać list. Powinno to być o jeden krok wcześniej. Już templatkę zrobiłem, a Django musi nadgonić. Wydaje mi się, że nie ma też opisu tego szablonu, który wymarzyłem sobie, że będzie nad przyciskiem.

Z wyrazami szacunku

**Comment by ad-m** [comment]
Nie rozumiem co sobie wymarzyłeś.
